// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.12
// source: Net_Login.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// xxxxccc曹操曹操传
type Net_Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 配表id
	Level int32     `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Wawa  *BuffData `protobuf:"bytes,3,opt,name=wawa,proto3" json:"wawa,omitempty"`
}

func (x *Net_Login) Reset() {
	*x = Net_Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Net_Login_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Net_Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Net_Login) ProtoMessage() {}

func (x *Net_Login) ProtoReflect() protoreflect.Message {
	mi := &file_Net_Login_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Net_Login.ProtoReflect.Descriptor instead.
func (*Net_Login) Descriptor() ([]byte, []int) {
	return file_Net_Login_proto_rawDescGZIP(), []int{0}
}

func (x *Net_Login) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Net_Login) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Net_Login) GetWawa() *BuffData {
	if x != nil {
		return x.Wawa
	}
	return nil
}

var File_Net_Login_proto protoreflect.FileDescriptor

var file_Net_Login_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x4e, 0x65, 0x74, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x11, 0x48, 0x6f, 0x74, 0x66, 0x69, 0x78, 0x2e, 0x4e, 0x65, 0x74, 0x2e, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x6c, 0x1a, 0x12, 0x4d, 0x79, 0x46, 0x69, 0x72, 0x73, 0x74, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x09, 0x4e, 0x65, 0x74, 0x5f,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x2f, 0x0a, 0x04, 0x77,
	0x61, 0x77, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x48, 0x6f, 0x74, 0x66,
	0x69, 0x78, 0x2e, 0x4e, 0x65, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x6c, 0x2e, 0x42, 0x75,
	0x66, 0x66, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x77, 0x61, 0x77, 0x61, 0x42, 0x06, 0x5a, 0x04,
	0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_Net_Login_proto_rawDescOnce sync.Once
	file_Net_Login_proto_rawDescData = file_Net_Login_proto_rawDesc
)

func file_Net_Login_proto_rawDescGZIP() []byte {
	file_Net_Login_proto_rawDescOnce.Do(func() {
		file_Net_Login_proto_rawDescData = protoimpl.X.CompressGZIP(file_Net_Login_proto_rawDescData)
	})
	return file_Net_Login_proto_rawDescData
}

var file_Net_Login_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Net_Login_proto_goTypes = []interface{}{
	(*Net_Login)(nil), // 0: Hotfix.Net.Protol.Net_Login
	(*BuffData)(nil),  // 1: Hotfix.Net.Protol.BuffData
}
var file_Net_Login_proto_depIdxs = []int32{
	1, // 0: Hotfix.Net.Protol.Net_Login.wawa:type_name -> Hotfix.Net.Protol.BuffData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Net_Login_proto_init() }
func file_Net_Login_proto_init() {
	if File_Net_Login_proto != nil {
		return
	}
	file_MyFirstProto_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_Net_Login_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Net_Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Net_Login_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Net_Login_proto_goTypes,
		DependencyIndexes: file_Net_Login_proto_depIdxs,
		MessageInfos:      file_Net_Login_proto_msgTypes,
	}.Build()
	File_Net_Login_proto = out.File
	file_Net_Login_proto_rawDesc = nil
	file_Net_Login_proto_goTypes = nil
	file_Net_Login_proto_depIdxs = nil
}
